apiVersion: v1
kind: Service
metadata:
  name: examination
  labels:
    group: example
spec:
  selector:
    app: exam-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
    # - protocol: 'TCP'
    #   port: 443
  type: LoadBalancer
